name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - dmehala
body:
  - type: markdown
    attributes:
      value: |
        Thank you for investing the time to complete this bug report.
        To ensure prompt attention and receive additional assistance, we suggest initiating a [Datadog support ticket](https://help.datadoghq.com/hc/en-us/requests/new) (no login required).
  - type: input
    id: kong-version
    attributes:
      label: Kong Version
      description: What version of Kong are you running?
      placeholder: Output of `kong version`
    validations:
      required: true
  - type: input
    id: ddtrace-version
    attributes:
      label: Plugin Version
      description: What version of `kong-plugin-ddtrace` are you running?
      placeholder: Output of `luarocks list kong-plugin-ddtrace`
    validations:
      required: true
  - type: dropdown
    id: runtime
    attributes:
      label: On which environment your Kong instance is running?
      options:
        - Kubernetes
        - Docker
        - Other
    validations:
      required: true
  - type: textarea
    id: ddtrace-config
    attributes:
      label: Plugin Configuration
      description: Please copy and paste the plugin configuration.
      render: yaml
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Detailed description of the problem, and if known, the expected behavior.
      value: "A bug happened!"
    validations:
      required: true
