version: '3.5'

services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
    - '/proc/:/host/proc/:ro'
    - '/sys/fs/cgroup/:/host/sys/fs/cgroup:ro'
    environment:
    - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
    - DD_API_KEY
    - DD_SITE
    networks:
    - ${NETWORK_NAME}
