name: System Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '00 04 * * *'

concurrency:
  # this ensures that only one workflow runs at a time for a given branch on pull requests
  # as the group key is the workflow name and the branch name
  # for scheduled runs and pushes to main, we use the run id to ensure that all runs are executed
  group: ${{ (github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.ref)) || format('{0}-{1}', github.workflow, github.run_id) }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4.3.1
      - run: mkdir -p artifact/kong-plugin-ddtrace && cp -r kong spec *.rockspec LICENSE README.md artifact/kong-plugin-ddtrace/
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: binaries
          path: artifact

  system-tests:
    needs: build
    uses: DataDog/system-tests/.github/workflows/system-tests.yml@main
    secrets:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      TEST_OPTIMIZATION_API_KEY: ${{ secrets.DD_API_KEY }}
    permissions:
      contents: read
      packages: write
    with:
      library: cpp_kong
      binaries_artifact: binaries
      scenarios: DEFAULT
      # On push/schedule, also run the broader tracer_release group; on PRs only DEFAULT
      scenarios_groups: ${{ (github.event_name == 'schedule' || github.event_name == 'push') && 'tracer_release' || '' }}
      skip_empty_scenarios: true
      push_to_test_optimization: ${{ github.actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}

  check:
    name: Check system tests success
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    needs: system-tests
    steps:
      - run: |
          if [[ "${{ needs.system-tests.result }}" != "success" ]]; then
            echo "System tests failed with result: ${{ needs.system-tests.result }}"
            exit 1
          fi
